name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  DOCKER_IMAGE_NAME: voltrondata/superset-sqlalchemy-adbc-flight-sql

jobs:
  docker:
    name: Build Docker images
    strategy:
      matrix:
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: ["self-hosted", "ubuntu-22.04-arm"] # This is self-hosted, change later...
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest-${{ matrix.platform }}
          no-cache: true
          provenance: false

  update-image-manifest:
    name: Update DockerHub image manifest to include all built platforms
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
        with:
          inputs: ${{ env.DOCKER_IMAGE_NAME }}:latest
          images: ${{ env.DOCKER_IMAGE_NAME }}:latest-amd64,${{ env.DOCKER_IMAGE_NAME }}:latest-arm64
          push: true
